name: BabyDoge Playwright Tests
on:
  push:
    branches:
      - flow
jobs:
  Testing_buying_using_boosters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: microsoft/playwright-github-action@v1
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install
    - name: Install Playwright Chromium
      run: npx playwright install-deps chromium
    - name: Run Playwright tests
      run: npx playwright test buyBoost.spec.ts --workers=5
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5
  
  # Testing_buying_using_cards:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: lts/*
  #   - uses: microsoft/playwright-github-action@v1
  #   - name: Install dependencies
  #     run: npm ci
  #   - name: Install Playwright
  #     run: npx playwright install
  #   - name: Install Playwright Chromium
  #     run: npx playwright install-deps chromium
  #   - name: Run Playwright tests
  #     run: npx playwright test buyCards.spec.ts
  #   - uses: actions/upload-artifact@v4
  #     if: ${{ !cancelled() }}
  #     with:
  #       name: playwright-report
  #       path: playwright-report/
  #       retention-days: 5
        
  # Testing_visibility_cards:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: actions/setup-node@v4
  #     with:
  #       node-version: lts/*
  #   - uses: microsoft/playwright-github-action@v1
  #   - name: Install dependencies
  #     run: npm ci
  #   - name: Install Playwright
  #     run: npx playwright install
  #   - name: Install Playwright Chromium
  #     run: npx playwright install-deps chromium
  #   - name: Run Playwright tests
  #     run: npx playwright test cards.spec.ts
  #   - uses: actions/upload-artifact@v4
  #     if: ${{ !cancelled() }}
  #     with:
  #       name: playwright-report
  #       path: playwright-report/
  #       retention-days: 5