name: BabyDoge Playwright Tests

on:
  push:
  workflow_dispatch:
  # Запуск по расписанию в 4:00 утра по Москве
  schedule:
    - cron: '0 1 * * *'  # 1:00 UTC соответствует 4:00 по московскому времени
  

jobs:
  Test_buy_use_boosters:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: microsoft/playwright-github-action@v1

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install

    - name: Install Playwright Chrome dependencies
      run: npx playwright install chrome

    - name: Install Allure for reporting
      run: |
        npm install -D allure-playwright
        npm install -g allure-commandline --save-dev
    - name: Run Playwright tests with Allure report
      run: npx playwright test buyBoost.spec.ts --reporter=line,allure-playwright

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: allure-results-boosters
        path: allure-results/
        retention-days: 10

  Test_buy_use_cards:
    runs-on: ubuntu-latest
    needs: Test_buy_use_boosters
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: microsoft/playwright-github-action@v1

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install

    - name: Install Playwright Chrome dependencies
      run: npx playwright install chrome

    - name: Install Allure for reporting
      run: |
        npm install -D allure-playwright
        npm install -g allure-commandline --save-dev
    - name: Run Playwright tests with Allure report
      run: npx playwright test buyCards.spec.ts --reporter=line,allure-playwright

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: allure-results-cards
        path: allure-results/
        retention-days: 10

  Test_visibility_cards:
    runs-on: ubuntu-latest
    needs: Test_buy_use_cards
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - uses: microsoft/playwright-github-action@v1

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install

    - name: Install Playwright Chrome dependencies
      run: npx playwright install chrome

    - name: Install Allure for reporting
      run: |
        npm install -D allure-playwright
        npm install -g allure-commandline --save-dev
    - name: Run Playwright tests with Allure report
      run: npx playwright test cards.spec.ts --reporter=line,allure-playwright

    - name: Create loginAuth.json from secret
      run: |
          echo '${{ secrets.LOGIN_AUTH_JSON }}' > LoginAuth2.json

    - name: Upload Allure results
      uses: actions/upload-artifact@v4
      if: ${{ always() }}
      with:
        name: allure-results-visibility
        path: allure-results/
        retention-days: 10