name: BabyDoge Playwright Tests

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]
  # schedule:             /// запуск по времени
  #   - cron: '0 1 * * *'
jobs:
  Test_buy_use_boosters:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    # Установка Playwright и зависимостей
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright
      run: npx playwright install

    # Создание файла loginAuth.json из секретов
    - name: Create loginAuth.json from secret
      run: |
        echo '${{ secrets.LOGIN_AUTH_JSON }}' > LoginAuth2.json
    
    # Запуск тестов
    - name: Run Playwright tests
      run: |
        npx playwright test --reporter=line,html

    # Копирование отчета в папку public
    - name: Copy Playwright report to a separate folder
      if: ${{ always() }}
      run: |
        mkdir -p public
        cp -r playwright-report/* public/

    # Развертывание отчета в GitHub Pages
    - name: Deploy report to GitHub Pages
      if: ${{ always() }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    # Печать ссылки на отчет
    - name: Print report URL
      if: ${{ always() }}
      run: |
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          REPORT_URL="https://${{ github.repository_owner }}.github.io/${REPO_NAME}/"
          echo "Before changes:"
          cat README.md
            FIRST_LINE="<strong>[HTML Report](${REPORT_URL})</strong>"
            REST_OF_FILE=$(tail -n +2 README.md)
            echo -e "$FIRST_LINE\n$REST_OF_FILE" > README.md
          echo "After changes:"
          cat README.md
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update README with latest HTML report link" || echo "No changes to commit"
          git push || echo "Nothing to push"
